import { createHash } from 'node:crypto';
import { inspectorClient, INSPECTOR_CSS } from './report-inspector.js';
import { UI_TEXT, languageClient } from './report-language.js';
import { REPORT_POLISH } from './report-style.js';
const embed = value => JSON.stringify(value).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');
export function renderLibraryReport(view, data, initial = 'en') {
  const script = `const language=(${languageClient.toString()})(${embed(UI_TEXT)},${embed(initial)});language.bindStatic(document.documentElement);(${libraryClient.toString()})(${embed(view)},${embed(data)},${inspectorClient.toString()},language);`;
  const hash = createHash('sha256').update(script).digest('base64');
  return `<!doctype html><html lang="${initial==='id'?'id':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${hash}'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Locator recovery report</title><style>${BASE_CSS}${INSPECTOR_CSS}${REPORT_POLISH}</style></head><body><div class="language-bar"><label for="report-language">Language / Bahasa</label><select id="report-language"><option value="en">English</option><option value="id">Bahasa Indonesia</option></select></div><nav class="rail"><strong>Self-healing</strong><span>Action evidence</span></nav><main id="overview-view"></main><main id="inspector-root" hidden></main><noscript>This offline report needs JavaScript to display recorded evidence. The summary is also available in report.json.</noscript><script>${script}</script></body></html>`;
}
function libraryClient(view, data, createInspector, language) {
  const t = language.text, ui = language.html;
  const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const overview = document.getElementById('overview-view');
  const inspector = createInspector(data, { ARMS: {run: {short:'',description:''}}, GROUPS:{library:'Library'}, CATEGORIES:{action:'Action'}, language });
  function result(row) { return t(row.wrong ? 'Wrong effect recorded' : row.operational ? 'Operational failure' : !row.assessed ? row.executed ? 'Action completed; correctness unassessed' : 'Stopped; correctness unassessed' : row.correct ? row.executed ? row.recovery ? 'Correct recovery' : 'Original action correct' : 'Stopped as expected' : 'Goal not achieved'); }
  function render() {
    overview.innerHTML = `<header><div class="topline"><div><p class="eyebrow">${esc(t('Action evidence'))}</p><h1>${esc(t('Locator recovery report'))}</h1></div><button id="summary-download">${esc(t('Download summary JSON'))}</button></div><p class="caption">${esc(view.id)} · ${esc(view.createdAt)} · ${esc(view.summary.evidenceKind)}</p><div class="stats">${[['Actions',view.summary.events],['Correct recoveries',view.summary.correctRepairs],['Wrong effects',view.summary.wrongEffects],['Unassessed',data.rows.filter(r=>!r.assessed).length]].map(([key,n])=>`<div><span>${esc(t(key))}</span><strong>${n}</strong></div>`).join('')}</div></header>
    <p class="caption">${esc(t('Select an action to inspect its DOM, AI input/output, checks and outcome.'))}</p>
    <div class="action-list">${data.rows.map(row=>`<article class="action-row"><div><p class="eyebrow">${esc(t('Action'))} ${row.caseId} · ${esc(row.audit.event.action)}</p><h2>${esc(row.title)}</h2><p class="result ${row.wrong?'wrong':''}">${esc(result(row))}</p><code>${esc(row.audit.event.originalSelector)}</code><p class="caption">${esc(t('Recovery attempts'))}: ${row.audit.attempts.length} · ${(row.totalMs/1000).toFixed(3)} s</p></div><button data-action="${esc(row.id)}">${esc(t('Inspect action'))} →</button></article>`).join('') || `<p>${esc(t('No actions recorded.'))}</p>`}</div>
    <details class="provenance"><summary>${esc(t('Evidence, sources and configuration'))}</summary><p>${esc(view.limitations)}</p><pre>${esc(JSON.stringify({config:view.config,summary:view.summary},null,2))}</pre></details>`;
    overview.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const row=data.rows.find(r=>r.id===button.dataset.action);inspector.open('library/'+row.caseId,{arm:'run',repeat:1});});
    document.getElementById('summary-download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(view,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='report-summary.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  }
  language.subscribe(render);
  render();
}
const BASE_CSS = `:root{--ink:#15393f;--teal:#18776b;--muted:#627476;--line:#d4ddd7;--red:#ad3f31}*{box-sizing:border-box}body{margin:0;color:var(--ink)}button,select{font:inherit;min-height:44px;border:1px solid #bdcec6;padding:9px 15px;border-radius:5px;background:white;color:var(--ink)}button,summary{cursor:pointer}button:hover{background:#edf3ef}button:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #437bb2;outline-offset:3px}summary{min-height:44px;padding:9px 0}h2{margin:0}pre{overflow:auto;background:#eef2ec;padding:16px}code,pre{font:12px/1.7 ui-monospace,monospace;overflow-wrap:anywhere}code{display:block}.topline{display:flex;justify-content:space-between;gap:20px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:var(--teal)}.caption{color:var(--muted);font-size:13px;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--line)}.stats span,.stats strong{display:block}.action-row{display:flex;align-items:center;justify-content:space-between;gap:22px;padding:24px 0;border-bottom:1px solid var(--line)}.action-row>div{min-width:0}.action-row h2{font-size:19px}.action-row button{flex-shrink:0}.action-row .result{margin-block:8px;font-size:14px}.wrong{color:var(--red)}footer{display:flex;justify-content:space-between;color:var(--muted)}.pill{font-size:12px}.language-bar{max-width:1280px;margin:auto;padding:12px 32px 0;display:flex;justify-content:flex-end;align-items:center;gap:12px;font-size:12px}.language-bar select{font-size:13px}.inspect-top>span{overflow-wrap:anywhere}@media(max-width:760px){.language-bar{padding:12px 16px 0}.action-row{display:block}.action-row button{margin-top:10px}.topline{flex-direction:column}}`;
