import { createHash } from 'node:crypto';
export interface SuiteRow {
  testId: string; title: string; file: string; project: string; retry: number;
  status: string; expectedStatus: string; durationMs: number; outcome: string;
  report: string | null; reportError: string | null;
}
export const escapeHtml = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function renderSuite(data: { status: string; rows: SuiteRow[]; createdAt: string }, initial: 'en' | 'id' = 'en'): string {
  const e = escapeHtml;
  const text = (en: string, id: string) => `<span data-en="${e(en)}" data-id="${e(id)}">${e(initial === 'en' ? en : id)}</span>`;
  const labels: Record<string, string> = { passed: 'lulus', failed: 'gagal', timedOut: 'batas waktu', interrupted: 'terhenti', skipped: 'dilewati', 'not-run': 'belum dijalankan', expected: 'sesuai harapan', unexpected: 'di luar harapan', flaky: 'lulus setelah retry', pending: 'belum selesai' };
  const tests = new Map(data.rows.map(row => [row.testId, row.outcome]));
  const script = `document.getElementById('language').addEventListener('change',e=>{const lang=e.target.value;document.documentElement.lang=lang;document.querySelectorAll('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);});`;
  const hash = createHash('sha256').update(script).digest('base64');
  return `<!doctype html><html lang="${initial}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${hash}'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Self-healing · Test results</title><style>
:root{font:16px/1.55 system-ui,sans-serif;color:#15393f;background:#f6f8f6}*{box-sizing:border-box}body{margin:0}main{max-width:1200px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}h1{font-size:32px;line-height:1.2;margin:8px 0}h2{font-size:17px;margin:0}a{color:#116858;text-underline-offset:3px}a:focus-visible,select:focus-visible{outline:3px solid #437bb2;outline-offset:3px}select{font:inherit;padding:8px;background:white;border:1px solid #bdcec6;border-radius:6px}.muted{color:#526869;font-size:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.stats>div{padding:16px;background:white;border:1px solid #d4ddd7;border-radius:8px}.stats strong{display:block;font-size:26px}article{background:white;border:1px solid #d4ddd7;border-radius:8px;padding:20px;margin:12px 0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px}article p{margin:6px 0;overflow-wrap:anywhere}h2{overflow-wrap:anywhere}.state{font-weight:650}.failed,.timedOut,.interrupted{color:#a53629}.passed{color:#146850}.notice{padding:12px 16px;border-left:3px solid #b7c9c2}footer{margin:24px 0}@media(max-width:620px){main{padding:16px}header,article{display:block}.stats{grid-template-columns:repeat(2,1fr)}header label{display:block;margin-top:16px}.report-link{display:inline-block;padding:10px 0}h1{font-size:26px}}
</style></head><body><main><header><div><p class="muted">SELF-HEALING · PLAYWRIGHT</p><h1>${text('Test results', 'Hasil tes')}</h1><p>${text('Suite status', 'Status keseluruhan')}: <strong>${text(data.status, labels[data.status] ?? data.status)}</strong></p><p class="muted">${e(data.createdAt)}</p></div><label>Language / Bahasa <select id="language"><option value="en" ${initial === 'en' ? 'selected' : ''}>English</option><option value="id" ${initial === 'id' ? 'selected' : ''}>Bahasa Indonesia</option></select></label></header>
<div class="stats"><div>${text('Tests', 'Tes')}<strong>${tests.size}</strong></div><div>${text('Recorded attempts', 'Percobaan tercatat')}<strong>${data.rows.filter(r => r.status !== 'not-run').length}</strong></div><div>${text('Unexpected outcomes', 'Hasil di luar harapan')}<strong>${[...tests.values()].filter(x => x === 'unexpected').length}</strong></div><div>${text('Reports unavailable', 'Report tidak tersedia')}<strong>${data.rows.filter(r => !r.report).length}</strong></div></div>
<p class="notice">${text('Playwright status describes the test. Action completion and independently assessed correctness are shown separately inside each report.', 'Status Playwright menjelaskan hasil tes. Aksi yang selesai dan ketepatan yang dinilai secara independen ditampilkan terpisah di dalam report.')}</p>
${data.rows.map(row => `<article><div><h2>${e(row.title)}</h2><p class="muted">${e(row.file)} · ${text('Project', 'Proyek')}: ${e(row.project || 'default')} · ${text('Retry', 'Ulangan')}: ${row.retry} · ${(row.durationMs / 1000).toFixed(2)} s</p><p class="state ${['passed','failed','timedOut','interrupted'].includes(row.status) ? row.status : ''}">${text('Test', 'Tes')}: ${text(row.status, labels[row.status] ?? row.status)} · ${text('Overall outcome', 'Hasil akhir')}: ${text(row.outcome, labels[row.outcome] ?? row.outcome)}</p>${row.status !== row.expectedStatus ? `<p class="muted">${text('Expected status', 'Status yang diharapkan')}: ${text(row.expectedStatus, labels[row.expectedStatus] ?? row.expectedStatus)}</p>` : ''}${row.reportError ? `<p class="muted">${text('Report unavailable', 'Report tidak tersedia')}: ${e(row.reportError)}</p>` : ''}</div><div>${row.report && /^actions\/[a-f0-9-]+\/report\.html$/.test(row.report) ? `<a class="report-link" href="${e(row.report)}">${text('Inspect actions', 'Periksa aksi')} →</a>` : ''}</div></article>`).join('') || `<p>${text('No tests recorded.', 'Belum ada tes yang direkam.')}</p>`}
<footer><a href="results.json">${text('Download test summary JSON', 'Unduh ringkasan tes JSON')}</a></footer></main><script>${script}</script></body></html>`;
}
